version: "3.9"

services:
  api:
    container_name: bovicare_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - DB_URL=postgresql://postgres:postgres@db:5432/bovicare
    depends_on:
      - db

  front:
    container_name: bovicare_web
    build:
      context: ../bovicare-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bovicare
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=kauanalexander123@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata: {}
  pgadmin_data: {}
